#!/bin/bash
# Check and tweet for most commonly
# requested Taps Aff location.

TTDIR=/home/pi/Taps-Tweeter/
PYTHON=/home/pi/Taps-Tweeter/env/bin/python

${PYTHON} ${TTDIR}/tapstweeter.py Glasgow
${PYTHON} ${TTDIR}/tapstweeter.py Edinburgh
${PYTHON} ${TTDIR}/tapstweeter.py London
${PYTHON} ${TTDIR}/tapstweeter.py Dundee
${PYTHON} ${TTDIR}/tapstweeter.py Aberdeen
${PYTHON} ${TTDIR}/tapstweeter.py Manchester
${PYTHON} ${TTDIR}/tapstweeter.py Stirling
${PYTHON} ${TTDIR}/tapstweeter.py Belfast
${PYTHON} ${TTDIR}/tapstweeter.py Falkirk
${PYTHON} ${TTDIR}/tapstweeter.py Perth
${PYTHON} ${TTDIR}/tapstweeter.py Inverness
${PYTHON} ${TTDIR}/tapstweeter.py Birmingham

date > ${TTDIR}/.last_ran

