#!/bin/bash
# Check and tweet for most commonly
# requested Taps Aff location.

TTDIR=/home/pi/Taps-Tweeter/

python ${TTDIR}/tapstweeter.py Glasgow
python ${TTDIR}/tapstweeter.py Edinburgh
python ${TTDIR}/tapstweeter.py London
python ${TTDIR}/tapstweeter.py Dundee
python ${TTDIR}/tapstweeter.py Aberdeen
python ${TTDIR}/tapstweeter.py Manchester
python ${TTDIR}/tapstweeter.py Stirling
python ${TTDIR}/tapstweeter.py Belfast
python ${TTDIR}/tapstweeter.py Falkirk
python ${TTDIR}/tapstweeter.py Perth
python ${TTDIR}/tapstweeter.py Inverness
python ${TTDIR}/tapstweeter.py Birmingham

date > ${TTDIR}/.last_ran

